// scripts/dedupeSchools.ts
import { writeFileSync } from "fs";
import universitiesData from "@/assets/data/schoolData";

const seen = new Map<string, (typeof universitiesData.universities)[number]>();

for (const uni of universitiesData.universities) {
  const key = uni.abbreviation.toUpperCase().trim();
  const existing = seen.get(key);

  if (!existing || Object.keys(uni).length > Object.keys(existing).length) {
    seen.set(key, uni);
  }
}

const deduped = Array.from(seen.values());
console.log(
  `Reduced ${universitiesData.universities.length} → ${deduped.length}`,
);

writeFileSync(
  "./src/assets/data/schoolData.cleaned.ts",
  `// Auto-generated by scripts/dedupeSchools.ts — review before replacing schoolData.ts

interface University {
  name: string;
  state: string;
  city: string;
  abbreviation: string;
  website: string;
  type?: string;
}

const universities: University[] = ${JSON.stringify(deduped, null, 2)};

const universitiesData = { universities };
export default universitiesData;
`,
);

console.log("Written to assets/data/schoolData.cleaned.ts");
